name: 'better-codecov-action'
description: 'codecov/codecov-action, but straightforward.'
branding:
  icon: 'umbrella'
  color: 'green'
inputs:
  arguments:
    description: 'Arguments to pass to the codecov uploader'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - name: Install codecov-cli from PyPI
      uses: install-pinned/codecov-cli@7a69c5cc0fc5de56089494e1dafca43807cac0b2  # 0.5.2
    - run: codecovcli do-upload ${{ inputs.arguments }}
      shell: bash
